services:
  - type: web
    name: iatrosense-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: GOOGLE_CLIENT_ID
        fromSecret: GOOGLE_CLIENT_ID
